### ISSUE TITLE
Baseline MAINTAINERS, CODEOWNERS, and external collaborator permissions

### ISSUE THREAD

**Issue by dblock** [opensearch-project/dashboards-i18n#17]
Follow https://github.com/opensearch-project/.github/issues/125 to baseline MAINTAINERS, CODEOWNERS, and external collaborator permissions.

Close this issue when:

1. [MAINTAINERS.md](MAINTAINERS.md) has the correct list of project maintainers.
2. [CODEOWNERS](CODEOWNERS) exists and has the correct list of aliases.
3. Repo permissions only contain individual aliases as collaborators with maintain rights, admin, and triage teams. 
4. All other teams are removed from repo permissions.

If this repo's permissions was already baselined, please confirm the above when closing this issue.

**Comment by dblock** [comment]
Permissions are incorrect. You have a group of 10+ people with maintain access. Please work with admin to sync.

![Screenshot 2023-03-23 at 10 56 59 AM](https://user-images.githubusercontent.com/542335/227243710-96560c48-8bea-4436-b32e-8347a16c9628.png)

**Comment by ananzh** [comment]
For the permission update, we don't have access. I will reach out to the build team to check if they could help. @bbarani @zelinh

**Comment by ananzh** [comment]
@zelinh,

Regarding the following two points:
* Repo permissions only contain individual aliases as collaborators with maintain rights, admin, and triage teams.
* All other teams are removed from repo permissions.

Is there some guide to know 1) who should have permissions? CODEOWNERS? 2) what permissions should we provide?

**Comment by zelinh** [comment]
After offline discussion with @ananzh, I believe she has the access to proceed here now.

**Comment by ananzh** [comment]
I have updated to this 

<img width="869" alt="Screenshot 2023-04-06 at 13 12 30" src="https://user-images.githubusercontent.com/79961084/230484611-4aaf501c-d3df-42d4-ab32-da6087e840a4.png">

**Comment by ananzh** [comment]
Since permissions are updated, will close this issue.

**Comment by dblock** [comment]
Verified, thx.
